2025-07-14 17:11:58,130 INFO    MainThread:276142 [wandb_setup.py:_flush():76] Current SDK version is 0.17.4
2025-07-14 17:11:58,130 INFO    MainThread:276142 [wandb_setup.py:_flush():76] Configure stats pid to 276142
2025-07-14 17:11:58,130 INFO    MainThread:276142 [wandb_setup.py:_flush():76] Loading settings from /home/aneek/.config/wandb/settings
2025-07-14 17:11:58,130 INFO    MainThread:276142 [wandb_setup.py:_flush():76] Loading settings from /home/aneek/LLM-Adapters/wandb/settings
2025-07-14 17:11:58,130 INFO    MainThread:276142 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-07-14 17:11:58,130 INFO    MainThread:276142 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-07-14 17:11:58,130 INFO    MainThread:276142 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'commonsense_evaluate.py', 'program_abspath': '/home/aneek/LLM-Adapters/commonsense_evaluate.py', 'program': '/home/aneek/LLM-Adapters/commonsense_evaluate.py'}
2025-07-14 17:11:58,130 INFO    MainThread:276142 [wandb_setup.py:_flush():76] Applying login settings: {}
2025-07-14 17:11:58,130 INFO    MainThread:276142 [wandb_init.py:_log_setup():529] Logging user logs to /home/aneek/LLM-Adapters/wandb/run-20250714_171158-ggipykfe/logs/debug.log
2025-07-14 17:11:58,130 INFO    MainThread:276142 [wandb_init.py:_log_setup():530] Logging internal logs to /home/aneek/LLM-Adapters/wandb/run-20250714_171158-ggipykfe/logs/debug-internal.log
2025-07-14 17:11:58,130 INFO    MainThread:276142 [wandb_init.py:init():569] calling init triggers
2025-07-14 17:11:58,130 INFO    MainThread:276142 [wandb_init.py:init():576] wandb.init called with sweep_config: {}
config: {'dataset': 'boolq', 'model': 'Llama-3.2-1B', 'adapter': 'LoRA', 'base_model': '/home/models/Llama-3.2-1B-Instruct/', 'lora_weights': '/home/aneek/LLM-Adapters/trained_models/llama-alpaca_data_cleaned-1B-lora', 'batch_size': 16, 'load_8bit': False}
2025-07-14 17:11:58,130 INFO    MainThread:276142 [wandb_init.py:init():619] starting backend
2025-07-14 17:11:58,130 INFO    MainThread:276142 [wandb_init.py:init():623] setting up manager
2025-07-14 17:11:58,132 INFO    MainThread:276142 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-07-14 17:11:58,133 INFO    MainThread:276142 [wandb_init.py:init():631] backend started and connected
2025-07-14 17:11:58,135 INFO    MainThread:276142 [wandb_init.py:init():720] updated telemetry
2025-07-14 17:11:58,138 INFO    MainThread:276142 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2025-07-14 17:13:28,157 ERROR   MainThread:276142 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2025-07-14 17:13:28,158 ERROR   MainThread:276142 [wandb_init.py:init():1191] error in wandb.init()
Traceback (most recent call last):
  File "/home/aneek/miniconda3/envs/llama4env/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    return wi.init()
  File "/home/aneek/miniconda3/envs/llama4env/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2025-07-14 17:13:29,225 WARNING MsgRouterThr:276142 [router.py:message_loop():77] message_loop has been closed
